# tesseract_config.yaml
version: "0.1.0"
name: heat_solver_diff
description: "Differentiable 1D Heat Equation solver using JAX"

# The execution environment
# build_config:
#   image_base: "python:3.10-slim"

# Define the endpoints we implemented
# endpoints:
#   apply:
#     module: tesseract_api
#     function: apply
    
#   vector_jacobian_product:
#     module: tesseract_api
#     function: vector_jacobian_product
    
#   jacobian:
#     module: tesseract_api
#     function: jacobian